// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import javax.persistence.Entity;
import nz.co.jsrsolutions.tideservice.core.domain.Operator;

privileged aspect Operator_Roo_Jpa_Entity {
    
    declare @type: Operator: @Entity;
    
}
