// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.util.List;
import nz.co.jsrsolutions.tideservice.core.domain.ClientDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.ClientIntegrationTest;
import nz.co.jsrsolutions.tideservice.core.repository.ClientRepository;
import nz.co.jsrsolutions.tideservice.core.service.ClientService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClientIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClientIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClientIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClientIntegrationTest: @Transactional;
    
    @Autowired
    private ClientDataOnDemand ClientIntegrationTest.dod;
    
    @Autowired
    ClientService ClientIntegrationTest.clientService;
    
    @Autowired
    ClientRepository ClientIntegrationTest.clientRepository;
    
    @Test
    public void ClientIntegrationTest.testCountAllClients() {
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = clientService.countAllClients();
        Assert.assertTrue("Counter for 'Client' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClientIntegrationTest.testFindClient() {
        Client obj = dod.getRandomClient();
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = clientService.findClient(id);
        Assert.assertNotNull("Find method for 'Client' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Client' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClientIntegrationTest.testFindAllClients() {
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = clientService.countAllClients();
        Assert.assertTrue("Too expensive to perform a find all test for 'Client', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Client> result = clientService.findAllClients();
        Assert.assertNotNull("Find all method for 'Client' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Client' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClientIntegrationTest.testFindClientEntries() {
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = clientService.countAllClients();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Client> result = clientService.findClientEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Client' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Client' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClientIntegrationTest.testFlush() {
        Client obj = dod.getRandomClient();
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = clientService.findClient(id);
        Assert.assertNotNull("Find method for 'Client' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClient(obj);
        Integer currentVersion = obj.getVersion();
        clientRepository.flush();
        Assert.assertTrue("Version for 'Client' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientIntegrationTest.testUpdateClientUpdate() {
        Client obj = dod.getRandomClient();
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = clientService.findClient(id);
        boolean modified =  dod.modifyClient(obj);
        Integer currentVersion = obj.getVersion();
        Client merged = (Client)clientService.updateClient(obj);
        clientRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Client' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientIntegrationTest.testSaveClient() {
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        Client obj = dod.getNewTransientClient(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Client' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Client' identifier to be null", obj.getId());
        clientService.saveClient(obj);
        clientRepository.flush();
        Assert.assertNotNull("Expected 'Client' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClientIntegrationTest.testDeleteClient() {
        Client obj = dod.getRandomClient();
        Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = clientService.findClient(id);
        clientService.deleteClient(obj);
        clientRepository.flush();
        Assert.assertNull("Failed to remove 'Client' with identifier '" + id + "'", clientService.findClient(id));
    }
    
}
