// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.util.List;
import nz.co.jsrsolutions.tideservice.core.domain.OperatorDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.OperatorIntegrationTest;
import nz.co.jsrsolutions.tideservice.core.repository.OperatorRepository;
import nz.co.jsrsolutions.tideservice.core.service.OperatorService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OperatorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OperatorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OperatorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OperatorIntegrationTest: @Transactional;
    
    @Autowired
    private OperatorDataOnDemand OperatorIntegrationTest.dod;
    
    @Autowired
    OperatorService OperatorIntegrationTest.operatorService;
    
    @Autowired
    OperatorRepository OperatorIntegrationTest.operatorRepository;
    
    @Test
    public void OperatorIntegrationTest.testCountAllOperators() {
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", dod.getRandomOperator());
        long count = operatorService.countAllOperators();
        Assert.assertTrue("Counter for 'Operator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OperatorIntegrationTest.testFindOperator() {
        Operator obj = dod.getRandomOperator();
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operator' failed to provide an identifier", id);
        obj = operatorService.findOperator(id);
        Assert.assertNotNull("Find method for 'Operator' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Operator' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OperatorIntegrationTest.testFindAllOperators() {
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", dod.getRandomOperator());
        long count = operatorService.countAllOperators();
        Assert.assertTrue("Too expensive to perform a find all test for 'Operator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Operator> result = operatorService.findAllOperators();
        Assert.assertNotNull("Find all method for 'Operator' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Operator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OperatorIntegrationTest.testFindOperatorEntries() {
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", dod.getRandomOperator());
        long count = operatorService.countAllOperators();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Operator> result = operatorService.findOperatorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Operator' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Operator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OperatorIntegrationTest.testFlush() {
        Operator obj = dod.getRandomOperator();
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operator' failed to provide an identifier", id);
        obj = operatorService.findOperator(id);
        Assert.assertNotNull("Find method for 'Operator' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOperator(obj);
        Integer currentVersion = obj.getVersion();
        operatorRepository.flush();
        Assert.assertTrue("Version for 'Operator' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OperatorIntegrationTest.testUpdateOperatorUpdate() {
        Operator obj = dod.getRandomOperator();
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operator' failed to provide an identifier", id);
        obj = operatorService.findOperator(id);
        boolean modified =  dod.modifyOperator(obj);
        Integer currentVersion = obj.getVersion();
        Operator merged = (Operator)operatorService.updateOperator(obj);
        operatorRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Operator' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OperatorIntegrationTest.testSaveOperator() {
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", dod.getRandomOperator());
        Operator obj = dod.getNewTransientOperator(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Operator' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Operator' identifier to be null", obj.getId());
        operatorService.saveOperator(obj);
        operatorRepository.flush();
        Assert.assertNotNull("Expected 'Operator' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OperatorIntegrationTest.testDeleteOperator() {
        Operator obj = dod.getRandomOperator();
        Assert.assertNotNull("Data on demand for 'Operator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operator' failed to provide an identifier", id);
        obj = operatorService.findOperator(id);
        operatorService.deleteOperator(obj);
        operatorRepository.flush();
        Assert.assertNull("Failed to remove 'Operator' with identifier '" + id + "'", operatorService.findOperator(id));
    }
    
}
