// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nz.co.jsrsolutions.tideservice.core.domain.AbstractUser;
import nz.co.jsrsolutions.tideservice.core.domain.Operator;
import nz.co.jsrsolutions.tideservice.core.domain.OperatorDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.repository.OperatorRepository;
import nz.co.jsrsolutions.tideservice.core.service.OperatorService;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OperatorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OperatorDataOnDemand: @Component;
    
    private Random OperatorDataOnDemand.rnd = new SecureRandom();
    
    private List<Operator> OperatorDataOnDemand.data;
    
    @Autowired
    OperatorService OperatorDataOnDemand.operatorService;
    
    @Autowired
    OperatorRepository OperatorDataOnDemand.operatorRepository;
    
    public Operator OperatorDataOnDemand.getNewTransientOperator(int index) {
        Operator obj = new Operator();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setFirstName(obj, index);
        setIsActive(obj, index);
        setLastModifiedBy(obj, index);
        setLastModifiedDate(obj, index);
        setLastName(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void OperatorDataOnDemand.setCreatedBy(Operator obj, int index) {
        AbstractUser createdBy = null;
        obj.setCreatedBy(createdBy);
    }
    
    public void OperatorDataOnDemand.setCreatedDate(Operator obj, int index) {
        DateTime createdDate = null;
        obj.setCreatedDate(createdDate);
    }
    
    public void OperatorDataOnDemand.setFirstName(Operator obj, int index) {
        String firstName = "firstName_" + index;
        if (firstName.length() > 100) {
            firstName = firstName.substring(0, 100);
        }
        obj.setFirstName(firstName);
    }
    
    public void OperatorDataOnDemand.setIsActive(Operator obj, int index) {
        Boolean isActive = Boolean.TRUE;
        obj.setIsActive(isActive);
    }
    
    public void OperatorDataOnDemand.setLastModifiedBy(Operator obj, int index) {
        AbstractUser lastModifiedBy = null;
        obj.setLastModifiedBy(lastModifiedBy);
    }
    
    public void OperatorDataOnDemand.setLastModifiedDate(Operator obj, int index) {
        DateTime lastModifiedDate = null;
        obj.setLastModifiedDate(lastModifiedDate);
    }
    
    public void OperatorDataOnDemand.setLastName(Operator obj, int index) {
        String lastName = "lastName_" + index;
        if (lastName.length() > 100) {
            lastName = lastName.substring(0, 100);
        }
        obj.setLastName(lastName);
    }
    
    public void OperatorDataOnDemand.setUserName(Operator obj, int index) {
        String userName = "userName_" + index;
        if (userName.length() > 80) {
            userName = userName.substring(0, 80);
        }
        obj.setUserName(userName);
    }
    
    public Operator OperatorDataOnDemand.getSpecificOperator(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Operator obj = data.get(index);
        Long id = obj.getId();
        return operatorService.findOperator(id);
    }
    
    public Operator OperatorDataOnDemand.getRandomOperator() {
        init();
        Operator obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return operatorService.findOperator(id);
    }
    
    public boolean OperatorDataOnDemand.modifyOperator(Operator obj) {
        return false;
    }
    
    public void OperatorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = operatorService.findOperatorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Operator' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Operator>();
        for (int i = 0; i < 10; i++) {
            Operator obj = getNewTransientOperator(i);
            try {
                operatorService.saveOperator(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            operatorRepository.flush();
            data.add(obj);
        }
    }
    
}
