// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.util.List;
import nz.co.jsrsolutions.tideservice.core.domain.SubAreaDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.SubAreaIntegrationTest;
import nz.co.jsrsolutions.tideservice.core.repository.SubAreaRepository;
import nz.co.jsrsolutions.tideservice.core.service.SubAreaService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SubAreaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubAreaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubAreaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SubAreaIntegrationTest: @Transactional;
    
    @Autowired
    private SubAreaDataOnDemand SubAreaIntegrationTest.dod;
    
    @Autowired
    SubAreaService SubAreaIntegrationTest.subAreaService;
    
    @Autowired
    SubAreaRepository SubAreaIntegrationTest.subAreaRepository;
    
    @Test
    public void SubAreaIntegrationTest.testCountAllSubAreas() {
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", dod.getRandomSubArea());
        long count = subAreaService.countAllSubAreas();
        Assert.assertTrue("Counter for 'SubArea' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubAreaIntegrationTest.testFindSubArea() {
        SubArea obj = dod.getRandomSubArea();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to provide an identifier", id);
        obj = subAreaService.findSubArea(id);
        Assert.assertNotNull("Find method for 'SubArea' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SubArea' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubAreaIntegrationTest.testFindAllSubAreas() {
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", dod.getRandomSubArea());
        long count = subAreaService.countAllSubAreas();
        Assert.assertTrue("Too expensive to perform a find all test for 'SubArea', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SubArea> result = subAreaService.findAllSubAreas();
        Assert.assertNotNull("Find all method for 'SubArea' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SubArea' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubAreaIntegrationTest.testFindSubAreaEntries() {
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", dod.getRandomSubArea());
        long count = subAreaService.countAllSubAreas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SubArea> result = subAreaService.findSubAreaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SubArea' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SubArea' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubAreaIntegrationTest.testFlush() {
        SubArea obj = dod.getRandomSubArea();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to provide an identifier", id);
        obj = subAreaService.findSubArea(id);
        Assert.assertNotNull("Find method for 'SubArea' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySubArea(obj);
        Integer currentVersion = obj.getVersion();
        subAreaRepository.flush();
        Assert.assertTrue("Version for 'SubArea' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubAreaIntegrationTest.testUpdateSubAreaUpdate() {
        SubArea obj = dod.getRandomSubArea();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to provide an identifier", id);
        obj = subAreaService.findSubArea(id);
        boolean modified =  dod.modifySubArea(obj);
        Integer currentVersion = obj.getVersion();
        SubArea merged = (SubArea)subAreaService.updateSubArea(obj);
        subAreaRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SubArea' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SubAreaIntegrationTest.testSaveSubArea() {
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", dod.getRandomSubArea());
        SubArea obj = dod.getNewTransientSubArea(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SubArea' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SubArea' identifier to be null", obj.getId());
        subAreaService.saveSubArea(obj);
        subAreaRepository.flush();
        Assert.assertNotNull("Expected 'SubArea' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubAreaIntegrationTest.testDeleteSubArea() {
        SubArea obj = dod.getRandomSubArea();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubArea' failed to provide an identifier", id);
        obj = subAreaService.findSubArea(id);
        subAreaService.deleteSubArea(obj);
        subAreaRepository.flush();
        Assert.assertNull("Failed to remove 'SubArea' with identifier '" + id + "'", subAreaService.findSubArea(id));
    }
    
}
