// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import nz.co.jsrsolutions.tideservice.core.domain.SubAreaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SubAreaDataOnDemand_Roo_Configurable {
    
    declare @type: SubAreaDataOnDemand: @Configurable;
    
}
