// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nz.co.jsrsolutions.tideservice.core.domain.AbstractUser;
import nz.co.jsrsolutions.tideservice.core.domain.Area;
import nz.co.jsrsolutions.tideservice.core.domain.AreaDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.SubArea;
import nz.co.jsrsolutions.tideservice.core.domain.SubAreaDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.repository.SubAreaRepository;
import nz.co.jsrsolutions.tideservice.core.service.SubAreaService;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubAreaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubAreaDataOnDemand: @Component;
    
    private Random SubAreaDataOnDemand.rnd = new SecureRandom();
    
    private List<SubArea> SubAreaDataOnDemand.data;
    
    @Autowired
    private AreaDataOnDemand SubAreaDataOnDemand.areaDataOnDemand;
    
    @Autowired
    SubAreaService SubAreaDataOnDemand.subAreaService;
    
    @Autowired
    SubAreaRepository SubAreaDataOnDemand.subAreaRepository;
    
    public SubArea SubAreaDataOnDemand.getNewTransientSubArea(int index) {
        SubArea obj = new SubArea();
        setArea(obj, index);
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setDescription(obj, index);
        setIsActive(obj, index);
        setLastModifiedBy(obj, index);
        setLastModifiedDate(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void SubAreaDataOnDemand.setArea(SubArea obj, int index) {
        Area area = areaDataOnDemand.getRandomArea();
        obj.setArea(area);
    }
    
    public void SubAreaDataOnDemand.setCreatedBy(SubArea obj, int index) {
        AbstractUser createdBy = null;
        obj.setCreatedBy(createdBy);
    }
    
    public void SubAreaDataOnDemand.setCreatedDate(SubArea obj, int index) {
        DateTime createdDate = null;
        obj.setCreatedDate(createdDate);
    }
    
    public void SubAreaDataOnDemand.setDescription(SubArea obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void SubAreaDataOnDemand.setIsActive(SubArea obj, int index) {
        Boolean isActive = Boolean.TRUE;
        obj.setIsActive(isActive);
    }
    
    public void SubAreaDataOnDemand.setLastModifiedBy(SubArea obj, int index) {
        AbstractUser lastModifiedBy = null;
        obj.setLastModifiedBy(lastModifiedBy);
    }
    
    public void SubAreaDataOnDemand.setLastModifiedDate(SubArea obj, int index) {
        DateTime lastModifiedDate = null;
        obj.setLastModifiedDate(lastModifiedDate);
    }
    
    public void SubAreaDataOnDemand.setName(SubArea obj, int index) {
        String name = "name_" + index;
        if (name.length() > 60) {
            name = name.substring(0, 60);
        }
        obj.setName(name);
    }
    
    public SubArea SubAreaDataOnDemand.getSpecificSubArea(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubArea obj = data.get(index);
        Long id = obj.getId();
        return subAreaService.findSubArea(id);
    }
    
    public SubArea SubAreaDataOnDemand.getRandomSubArea() {
        init();
        SubArea obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return subAreaService.findSubArea(id);
    }
    
    public boolean SubAreaDataOnDemand.modifySubArea(SubArea obj) {
        return false;
    }
    
    public void SubAreaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = subAreaService.findSubAreaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubArea' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubArea>();
        for (int i = 0; i < 10; i++) {
            SubArea obj = getNewTransientSubArea(i);
            try {
                subAreaService.saveSubArea(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            subAreaRepository.flush();
            data.add(obj);
        }
    }
    
}
