// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nz.co.jsrsolutions.tideservice.core.domain.AbstractUser;
import nz.co.jsrsolutions.tideservice.core.domain.Port;
import nz.co.jsrsolutions.tideservice.core.domain.PortDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionDay;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionDayDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.repository.TidePredictionDayRepository;
import nz.co.jsrsolutions.tideservice.core.service.TidePredictionDayService;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TidePredictionDayDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TidePredictionDayDataOnDemand: @Component;
    
    private Random TidePredictionDayDataOnDemand.rnd = new SecureRandom();
    
    private List<TidePredictionDay> TidePredictionDayDataOnDemand.data;
    
    @Autowired
    private PortDataOnDemand TidePredictionDayDataOnDemand.portDataOnDemand;
    
    @Autowired
    TidePredictionDayService TidePredictionDayDataOnDemand.tidePredictionDayService;
    
    @Autowired
    TidePredictionDayRepository TidePredictionDayDataOnDemand.tidePredictionDayRepository;
    
    public TidePredictionDay TidePredictionDayDataOnDemand.getNewTransientTidePredictionDay(int index) {
        TidePredictionDay obj = new TidePredictionDay();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setIsActive(obj, index);
        setLastModifiedBy(obj, index);
        setLastModifiedDate(obj, index);
        setLocalDate(obj, index);
        setPort(obj, index);
        return obj;
    }
    
    public void TidePredictionDayDataOnDemand.setCreatedBy(TidePredictionDay obj, int index) {
        AbstractUser createdBy = null;
        obj.setCreatedBy(createdBy);
    }
    
    public void TidePredictionDayDataOnDemand.setCreatedDate(TidePredictionDay obj, int index) {
        DateTime createdDate = null;
        obj.setCreatedDate(createdDate);
    }
    
    public void TidePredictionDayDataOnDemand.setIsActive(TidePredictionDay obj, int index) {
        Boolean isActive = Boolean.TRUE;
        obj.setIsActive(isActive);
    }
    
    public void TidePredictionDayDataOnDemand.setLastModifiedBy(TidePredictionDay obj, int index) {
        AbstractUser lastModifiedBy = null;
        obj.setLastModifiedBy(lastModifiedBy);
    }
    
    public void TidePredictionDayDataOnDemand.setLastModifiedDate(TidePredictionDay obj, int index) {
        DateTime lastModifiedDate = null;
        obj.setLastModifiedDate(lastModifiedDate);
    }
    
    public void TidePredictionDayDataOnDemand.setLocalDate(TidePredictionDay obj, int index) {
        LocalDate localDate = null;
        obj.setLocalDate(localDate);
    }
    
    public void TidePredictionDayDataOnDemand.setPort(TidePredictionDay obj, int index) {
        Port port = portDataOnDemand.getRandomPort();
        obj.setPort(port);
    }
    
    public TidePredictionDay TidePredictionDayDataOnDemand.getSpecificTidePredictionDay(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TidePredictionDay obj = data.get(index);
        Long id = obj.getId();
        return tidePredictionDayService.findTidePredictionDay(id);
    }
    
    public TidePredictionDay TidePredictionDayDataOnDemand.getRandomTidePredictionDay() {
        init();
        TidePredictionDay obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return tidePredictionDayService.findTidePredictionDay(id);
    }
    
    public boolean TidePredictionDayDataOnDemand.modifyTidePredictionDay(TidePredictionDay obj) {
        return false;
    }
    
    public void TidePredictionDayDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = tidePredictionDayService.findTidePredictionDayEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TidePredictionDay' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TidePredictionDay>();
        for (int i = 0; i < 10; i++) {
            TidePredictionDay obj = getNewTransientTidePredictionDay(i);
            try {
                tidePredictionDayService.saveTidePredictionDay(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            tidePredictionDayRepository.flush();
            data.add(obj);
        }
    }
    
}
