// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.util.List;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionDayDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionDayIntegrationTest;
import nz.co.jsrsolutions.tideservice.core.repository.TidePredictionDayRepository;
import nz.co.jsrsolutions.tideservice.core.service.TidePredictionDayService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TidePredictionDayIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TidePredictionDayIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TidePredictionDayIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TidePredictionDayIntegrationTest: @Transactional;
    
    @Autowired
    private TidePredictionDayDataOnDemand TidePredictionDayIntegrationTest.dod;
    
    @Autowired
    TidePredictionDayService TidePredictionDayIntegrationTest.tidePredictionDayService;
    
    @Autowired
    TidePredictionDayRepository TidePredictionDayIntegrationTest.tidePredictionDayRepository;
    
    @Test
    public void TidePredictionDayIntegrationTest.testCountAllTidePredictionDays() {
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", dod.getRandomTidePredictionDay());
        long count = tidePredictionDayService.countAllTidePredictionDays();
        Assert.assertTrue("Counter for 'TidePredictionDay' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testFindTidePredictionDay() {
        TidePredictionDay obj = dod.getRandomTidePredictionDay();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to provide an identifier", id);
        obj = tidePredictionDayService.findTidePredictionDay(id);
        Assert.assertNotNull("Find method for 'TidePredictionDay' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TidePredictionDay' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testFindAllTidePredictionDays() {
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", dod.getRandomTidePredictionDay());
        long count = tidePredictionDayService.countAllTidePredictionDays();
        Assert.assertTrue("Too expensive to perform a find all test for 'TidePredictionDay', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TidePredictionDay> result = tidePredictionDayService.findAllTidePredictionDays();
        Assert.assertNotNull("Find all method for 'TidePredictionDay' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TidePredictionDay' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testFindTidePredictionDayEntries() {
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", dod.getRandomTidePredictionDay());
        long count = tidePredictionDayService.countAllTidePredictionDays();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TidePredictionDay> result = tidePredictionDayService.findTidePredictionDayEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TidePredictionDay' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TidePredictionDay' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testFlush() {
        TidePredictionDay obj = dod.getRandomTidePredictionDay();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to provide an identifier", id);
        obj = tidePredictionDayService.findTidePredictionDay(id);
        Assert.assertNotNull("Find method for 'TidePredictionDay' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTidePredictionDay(obj);
        Integer currentVersion = obj.getVersion();
        tidePredictionDayRepository.flush();
        Assert.assertTrue("Version for 'TidePredictionDay' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testUpdateTidePredictionDayUpdate() {
        TidePredictionDay obj = dod.getRandomTidePredictionDay();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to provide an identifier", id);
        obj = tidePredictionDayService.findTidePredictionDay(id);
        boolean modified =  dod.modifyTidePredictionDay(obj);
        Integer currentVersion = obj.getVersion();
        TidePredictionDay merged = (TidePredictionDay)tidePredictionDayService.updateTidePredictionDay(obj);
        tidePredictionDayRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TidePredictionDay' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testSaveTidePredictionDay() {
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", dod.getRandomTidePredictionDay());
        TidePredictionDay obj = dod.getNewTransientTidePredictionDay(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TidePredictionDay' identifier to be null", obj.getId());
        tidePredictionDayService.saveTidePredictionDay(obj);
        tidePredictionDayRepository.flush();
        Assert.assertNotNull("Expected 'TidePredictionDay' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TidePredictionDayIntegrationTest.testDeleteTidePredictionDay() {
        TidePredictionDay obj = dod.getRandomTidePredictionDay();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePredictionDay' failed to provide an identifier", id);
        obj = tidePredictionDayService.findTidePredictionDay(id);
        tidePredictionDayService.deleteTidePredictionDay(obj);
        tidePredictionDayRepository.flush();
        Assert.assertNull("Failed to remove 'TidePredictionDay' with identifier '" + id + "'", tidePredictionDayService.findTidePredictionDay(id));
    }
    
}
