// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nz.co.jsrsolutions.tideservice.core.domain;

import java.util.List;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionDataOnDemand;
import nz.co.jsrsolutions.tideservice.core.domain.TidePredictionIntegrationTest;
import nz.co.jsrsolutions.tideservice.core.repository.TidePredictionRepository;
import nz.co.jsrsolutions.tideservice.core.service.TidePredictionService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TidePredictionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TidePredictionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TidePredictionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TidePredictionIntegrationTest: @Transactional;
    
    @Autowired
    private TidePredictionDataOnDemand TidePredictionIntegrationTest.dod;
    
    @Autowired
    TidePredictionService TidePredictionIntegrationTest.tidePredictionService;
    
    @Autowired
    TidePredictionRepository TidePredictionIntegrationTest.tidePredictionRepository;
    
    @Test
    public void TidePredictionIntegrationTest.testCountAllTidePredictions() {
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", dod.getRandomTidePrediction());
        long count = tidePredictionService.countAllTidePredictions();
        Assert.assertTrue("Counter for 'TidePrediction' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TidePredictionIntegrationTest.testFindTidePrediction() {
        TidePrediction obj = dod.getRandomTidePrediction();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to provide an identifier", id);
        obj = tidePredictionService.findTidePrediction(id);
        Assert.assertNotNull("Find method for 'TidePrediction' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TidePrediction' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TidePredictionIntegrationTest.testFindAllTidePredictions() {
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", dod.getRandomTidePrediction());
        long count = tidePredictionService.countAllTidePredictions();
        Assert.assertTrue("Too expensive to perform a find all test for 'TidePrediction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TidePrediction> result = tidePredictionService.findAllTidePredictions();
        Assert.assertNotNull("Find all method for 'TidePrediction' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TidePrediction' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TidePredictionIntegrationTest.testFindTidePredictionEntries() {
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", dod.getRandomTidePrediction());
        long count = tidePredictionService.countAllTidePredictions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TidePrediction> result = tidePredictionService.findTidePredictionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TidePrediction' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TidePrediction' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TidePredictionIntegrationTest.testFlush() {
        TidePrediction obj = dod.getRandomTidePrediction();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to provide an identifier", id);
        obj = tidePredictionService.findTidePrediction(id);
        Assert.assertNotNull("Find method for 'TidePrediction' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTidePrediction(obj);
        Integer currentVersion = obj.getVersion();
        tidePredictionRepository.flush();
        Assert.assertTrue("Version for 'TidePrediction' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TidePredictionIntegrationTest.testUpdateTidePredictionUpdate() {
        TidePrediction obj = dod.getRandomTidePrediction();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to provide an identifier", id);
        obj = tidePredictionService.findTidePrediction(id);
        boolean modified =  dod.modifyTidePrediction(obj);
        Integer currentVersion = obj.getVersion();
        TidePrediction merged = (TidePrediction)tidePredictionService.updateTidePrediction(obj);
        tidePredictionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TidePrediction' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TidePredictionIntegrationTest.testSaveTidePrediction() {
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", dod.getRandomTidePrediction());
        TidePrediction obj = dod.getNewTransientTidePrediction(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TidePrediction' identifier to be null", obj.getId());
        tidePredictionService.saveTidePrediction(obj);
        tidePredictionRepository.flush();
        Assert.assertNotNull("Expected 'TidePrediction' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TidePredictionIntegrationTest.testDeleteTidePrediction() {
        TidePrediction obj = dod.getRandomTidePrediction();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TidePrediction' failed to provide an identifier", id);
        obj = tidePredictionService.findTidePrediction(id);
        tidePredictionService.deleteTidePrediction(obj);
        tidePredictionRepository.flush();
        Assert.assertNull("Failed to remove 'TidePrediction' with identifier '" + id + "'", tidePredictionService.findTidePrediction(id));
    }
    
}
